import type { Metadata } from "next";
import "./globals.css";
import Providers from "../providers/providers";

export const metadata: Metadata = {
	title: "Freelanceify | simplifies the freelance experiences",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="fa" dir="rtl">
			<body>
				<Providers>
					<div>{children}</div>
				</Providers>
			</body>
		</html>
	);
}
